Numpy Practice Questions

In [2]:
import numpy as np

In [3]:
# 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
# Define two custom numpy arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Stack A and B vertically
vertical_stack = np.vstack((A, B))

# Stack A and B horizontally
horizontal_stack = np.hstack((A, B))

# Print the results
print("Vertical Stack:")
print(vertical_stack)

print("\nHorizontal Stack:")
print(horizontal_stack)

Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]


In [4]:
# 2. Find common elements between A and B. [Hint : Intersection of two sets]
# Define two custom numpy arrays
A = np.array([1, 2, 3, 4])
B = np.array([3, 4, 5, 6])

# Find the common elements between A and B
common_elements = np.intersect1d(A, B)

# Print the common elements
print("Common elements between A and B:")
print(common_elements)

Common elements between A and B:
[3 4]


In [6]:
# 3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
# Define a custom numpy array
A = np.array([1, 2, 3, 4, 6, 8, 10, 12])

# Find indices where the condition is True
indices = np.where((A >= 5) & (A <= 10))

# Extract numbers using the indices
extracted_numbers = A[indices]

# Print the extracted numbers
print("Numbers between 5 and 10 in array A:")
print(extracted_numbers)

Numbers between 5 and 10 in array A:
[ 6  8 10]


In [8]:
# 4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
# Fetching the iris_2d data
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Filtering the rows based on the conditions
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

# Print the filtered rows
print("Filtered rows:")
print(filtered_rows)

Filtered rows:
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


Practice Questions for Pandas

In [10]:
import pandas as pd

In [11]:
# 1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df1 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
# Filter the specified columns for every 20th row
filtered_df = df1.iloc[::20][['Manufacturer', 'Model', 'Type']]

print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [12]:
# 2. Replace missing values in Min.Price and Max.Price columns with their respective mean.
df2 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Replace missing values with the mean of the respective column
df2['Min.Price'].fillna(df2['Min.Price'].mean(), inplace=True)
df2['Max.Price'].fillna(df2['Max.Price'].mean(), inplace=True)

print(df2[['Min.Price', 'Max.Price']].head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [13]:
# 3. How to get the rows of a dataframe with row sum > 100?
df3 = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Filter rows where row sum is greater than 100
result = df3[df3.sum(axis=1) > 100]

print(result)

     0   1   2   3
0   31  17  28  26
5   26  25  35  38
8   33  11  38  38
11  19  37  26  29
14  33  38  24  12
